name: GitHub Actions Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.x

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: |
            python -m pip install --upgrade pip
            python -m pip install -r requirements.txt
            pytest

      - name: Capture error logs
        run: python capture_error_logs.py

      - name: Display error logs
        run: cat error_logs.txt

      - name: Upload error logs
        uses: actions/upload-artifact@v2
        with:
          name: error-logs
          path: error_logs.txt
