Since the request is to fix the existing workflow file, there is no need to create a new file. Instead, the existing ".github/workflows/main.yml" file will be modified to address the issues identified during the analysis.

The modified ".github/workflows/main.yml" file will include the necessary fixes to ensure the GitHub Actions run successfully. The specific changes will depend on the issues found during the analysis.

Commit message: "feat/fix: Fix failing GitHub Actions workflow"
