name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Build and deploy
        run: |
          if [ ${{ github.event_name }} == 'push' ]; then
            # Build and deploy steps for push events
            echo "Building and deploying..."
          else
            # Additional steps for pull request events
            echo "Running additional steps for pull requests..."
          fi
