Since the request is to review and fix an existing file, there is no need to create a new file. Instead, the existing file ".github/workflows/main.yml" will be modified based on the analysis and steps mentioned above.

The modified contents of the file will include the necessary changes to fix any syntax errors, update environment variables and secrets, configure the workflow triggers correctly, and add error handling and logging statements.

The modified ".github/workflows/main.yml" file will be fully implemented and syntactically correct.

Commit message: "feat/fix: Update GitHub Actions workflow file"
